---
- name: Ensure QEMU guest agent is installed
  become: true
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  when: ansible_system_vendor == 'QEMU'

- name: Ensure QEMU guest agent is enabled
  ansible.builtin.service:
    name: qemu-guest-agent
    enabled: true
  when: ansible_system_vendor == 'QEMU'
